# Numpy Basics

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,9]], np.int64)

In [3]:
myarr

array([[ 3,  6, 37,  9]], dtype=int64)

In [4]:
myarr[0]

array([ 3,  6, 37,  9], dtype=int64)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0,1]

6

In [8]:
myarr[0,1]=10

In [9]:
myarr[0,1]

10

In [10]:
myarr

array([[ 3, 10, 37,  9]], dtype=int64)

**Array creation**

In [11]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({1,2,3,4,5,6,7,8,9})

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [17]:
zeros = np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
zeros.size

10

In [22]:
rng = np.arange(15)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,50,10)

In [25]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
lspace = np.linspace(1,5,5)

In [27]:
lspace

array([1., 2., 3., 4., 5.])

In [28]:
emp = np.empty((4,5))

In [29]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.24610723e-306, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306],
       [2.22518251e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 3.11525958e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.33511562e-306]])

In [30]:
emp_like = np.empty_like(lspace)

In [31]:
emp_like

array([1., 2., 3., 4., 5.])

In [32]:
ide = np.identity(5)

In [33]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
ide.shape

(5, 5)

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr = arr.reshape(3,33)

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
arr = arr.ravel()

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(99,)

In [43]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr = listarray

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.sum(axis=0)

array([12, 15, 18])

In [47]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Transpose Array**

In [49]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Array iterator**

In [50]:
arr.flat

In [51]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


**Array Dimension**

In [52]:
arr.ndim

2

In [53]:
arr.size

9

In [54]:
arr.nbytes

36

In [55]:
one = np.array([1,2,5,36,8])

**Max,Min,Sort Element Index**

In [56]:
one.argmax()

3

In [57]:
one.argmin()

0

In [58]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.argmax()

8

In [61]:
arr.argmin()

0

In [62]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [63]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [64]:
arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [65]:
arr.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [66]:
arr.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [67]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [68]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

**Matrix Operation**

In [69]:
arr1 = arr

In [70]:
arr2 = np.array([[9,8,7],[6,5,4,],[3,2,1]])

In [71]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [73]:
arr1+arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [74]:
arr1*arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [75]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [77]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [78]:
arr2.sum()

45

In [79]:
arr2.max()

9

In [80]:
arr2.min()

1

In [81]:
arr2.sort()

In [82]:
arr2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [83]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
np.where(arr>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [85]:
type(np.where(arr>5))

tuple

In [86]:
np.count_nonzero(arr)

9

In [87]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [88]:
import sys

In [89]:
py_arr = [1,2,3,4,5]

In [90]:
np_arr = np.array(py_arr)

In [91]:
sys.getsizeof(1) * len(py_arr)

140

In [92]:
np_arr.itemsize * np_arr.size

20

In [93]:
np_arr.tolist()

[1, 2, 3, 4, 5]

In [94]:
import numpy as np

In [95]:
arr = np.array([1,2,3])

In [96]:
scaler = 2

In [97]:
result = arr + scaler

In [98]:
result

array([3, 4, 5])

In [99]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

reshaped = arr.reshape(3, 2)  # Reshape to 3 rows and 2 columns
vertical_stack = np.vstack((arr, arr))  # Stack arrays vertically
horizontal_stack = np.hstack((arr, arr))  # Stack arrays horizontally


In [100]:
vertical_stack

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [101]:
horizontal_stack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [102]:
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])